name: acctally
description: "Cost Sales BEP Calculator Application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^1.0.1
  path: ^1.9.0
  shared_preferences: ^2.2.2
  logger: ^2.0.0
  get: ^4.6.6
  intl: ^0.20.2
  another_flushbar: ^1.12.29
  google_fonts: ^6.1.0
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  iconify_flutter: ^0.0.7
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.13.1

flutter_gen:
  output: lib/core/utils/ # Optional (default: lib/gen/)
  # line_length: 80 # Optional

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/images/

    # Icons
    - assets/icons/
